import type { Metadata } from "next"
export const metadata: Metadata = { title: "ForgeOS App", description: "Generated by ForgeOS Node Studio" }
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body>{children}</body></html>
}
